### ISSUE TITLE
onDraggedPin Returns NaN Problem

### ISSUE THREAD

**Issue by codeyoma** [art29/react-image-pin#2]
First of all, thank you for this project.
It’s been incredibly helpful in streamlining my development process.

---

### Issue:
I’m encountering an issue where `onDraggedPin` returns NaN for the pin’s coordinates after dragging. 

- my code
``` tsx
<ImagePinContainer
  image={image ?? defaultImage}
  imageAlt="A beautiful image"
  pins={pins}
  draggable={true}
  onDraggedPin={(pin) => {
     console.log('onDraggedPin', pin);
  }}
  onNewPin={(pin) => {
     console.log('onNewPin', pin);
  }}
  onExistingPin={(pin) => {
     console.log('onExistingPin', pin);
  }}
/>
```

- console
`onDraggedPin NaN NaN`

---

### Expected Behavior
After dragging a pin, `onDraggedPin` should return the updated positionX and positionY values of the pin.

---

### Actual Behavior
`onDraggedPin` logs NaN for positionX and positionY after dragging.

Is there something I’m missing in the implementation, or could this be a potential bug?

**Comment by art29** [comment]
Hello ! 
Thank you for your kind message. 
I tried the issue you were pointing, did you make sure to add `draggable: true` to your pins themselves?

I made you a little demo that seems to work (I also updated the readme as it was out of date): https://stackblitz.com/edit/vitejs-vite-vkkws2?file=src%2FApp.tsx

Let me know if you figure it out with that or if you still need help!

**Comment by codeyoma** [comment]
It seems like there might be an issue with the browser itself. 

When testing in Chrome, the issue doesn’t appear with one specific profile, but it does with another. However, when using Safari, it works fine. 

Currently, it’s working well, and I appreciate your help. 

Thank you!
